name: App - Build and Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - "app/**"
      - "k8s/**"
      - ".github/workflows/app.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_DIR: iac/terraform
  AWS_ROLE_ARN: "REPLACE_ME_WITH_GITHUB_OIDC_ROLE_ARN"
  IMAGE_TAG: "ci-${{ github.sha }}"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init (read outputs)
        run: terraform -chdir=${{ env.TF_DIR }} init

      - name: Read Terraform outputs
        id: tf
        run: |
          echo "ECR=$(terraform -chdir=${{ env.TF_DIR }} output -raw ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "CLUSTER=$(terraform -chdir=${{ env.TF_DIR }} output -raw eks_cluster_name)" >> $GITHUB_OUTPUT
          echo "MONGO_IP=$(terraform -chdir=${{ env.TF_DIR }} output -raw mongo_private_ip)" >> $GITHUB_OUTPUT

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        working-directory: app
        run: |
          docker build -t wizapp:${{ env.IMAGE_TAG }} .
          docker tag wizapp:${{ env.IMAGE_TAG }} ${{ steps.tf.outputs.ECR }}:${{ env.IMAGE_TAG }}

      - name: Container scan (Trivy)
        uses: aquasecurity/trivy-action@0.25.0
        with:
          image-ref: "wizapp:${{ env.IMAGE_TAG }}"
          format: "table"
          exit-code: "0"

      - name: Push image
        run: docker push ${{ steps.tf.outputs.ECR }}:${{ env.IMAGE_TAG }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ steps.tf.outputs.CLUSTER }}

      - name: Deploy to Kubernetes
        run: |
          chmod +x k8s/overlays/dev/deploy.sh
          k8s/overlays/dev/deploy.sh             --image "${{ steps.tf.outputs.ECR }}:${{ env.IMAGE_TAG }}"             --mongo_ip "${{ steps.tf.outputs.MONGO_IP }}"             --mongo_user "wizuser"             --mongo_pass "wizpass"
